// SPDX-License-Identifier: AGPL-3.0-only
// Loombre :: packages/provisioning-pg/src/hba.ts
//
// P4.2 "pg_hba locked to localhost+password". initdb's own generated
// pg_hba.conf already restricts to local/127.0.0.1/::1 with scram-sha-256
// by default (verified for real on the vendored 17.10.0 binary — see this
// lane's report) — this package does NOT trust that default to hold across
// binary re-pins, though: it OVERWRITES pg_hba.conf with this deterministic,
// minimal, auditable content instead, every time provision() runs initdb.
// Deliberately narrower than initdb's own default: no `replication`
// entries (Loombre's embedded instance never replicates), local + IPv4/IPv6
// loopback only, scram-sha-256 (the strongest password method PostgreSQL
// ships) for every entry — no `trust`, ever.

export const PG_HBA_CONTENTS =
  "# Generated by @loombre/provisioning-pg — do not hand-edit (provision() overwrites this file).\n" +
  "# Localhost + password only (STATE.md P4.2). No replication entries; no `trust`.\n" +
  "local   all             all                                     scram-sha-256\n" +
  "host    all             all             127.0.0.1/32            scram-sha-256\n" +
  "host    all             all             ::1/128                 scram-sha-256\n";
