#!/usr/bin/env node
// scripts/ui-audit/stylelint-planted.mjs — run UIFIX-2026-08-29 feedback
// harness, artefact 2.
//
// A planted-violation check for the stylelint feedback loop. It proves the
// linter can actually SEE the two design-law violations the run cares about,
// rather than assuming a rule exists because a config file mentions one:
//
//   radiusCaught — `border-radius: 11px` must be rejected by the radius
//                  allowed-list (.stylelintrc.json:15-27). TRUE today.
//   gapCaught    — `gap: 13px` must be rejected by a spacing-scale rule.
//                  FALSE today; authoring that rule is Wave-2 work (W2-B).
//
// EXPECTED TODAY (--expect=baseline): radiusCaught=true, gapCaught=false.
// AFTER W2-B     (--expect=final):    both true.
//
// The failing half is the point: a harness that passes before the work is done
// is not a feedback loop. Wave gates flip the flag; they do not edit this file.
//
// Zero dependencies, plain node ESM (UD-12). The probe CSS is written to the
// OS temp dir and removed in a finally block — NEVER inside apps/web/src, where
// it would be picked up by `pnpm lint`, the jsdom specs that read .module.css
// text, and the ld14-conformance walk.
//
// Usage:
//   node scripts/ui-audit/stylelint-planted.mjs                  # report only, exit 0
//   node scripts/ui-audit/stylelint-planted.mjs --expect=baseline # exit 1 on mismatch
//   node scripts/ui-audit/stylelint-planted.mjs --expect=final    # exit 1 on mismatch
//   node scripts/ui-audit/stylelint-planted.mjs --json

import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const WEB_DIR = join(REPO_ROOT, 'apps', 'web');
const CONFIG = '.stylelintrc.json'; // resolved relative to WEB_DIR (the cwd below)
const LOCAL_BIN = join(WEB_DIR, 'node_modules', '.bin', 'stylelint');

// Multi-line on purpose: the single-line form `.x { gap: 13px; border-radius:
// 11px; }` additionally trips declaration-block-single-line-max-declarations,
// which is unrelated noise and would muddy the two signals being measured.
const PROBE_CSS = `.x {
  gap: 13px;
  border-radius: 11px;
}
`;

const EXPECTATIONS = {
  baseline: { radiusCaught: true, gapCaught: false },
  final: { radiusCaught: true, gapCaught: true },
};

const args = process.argv.slice(2);
const jsonOut = args.includes('--json');
const expectArg = args.find((a) => a.startsWith('--expect='));
const expectKey = expectArg ? expectArg.slice('--expect='.length) : null;

if (expectKey && !(expectKey in EXPECTATIONS)) {
  process.stderr.write(
    `stylelint-planted: unknown --expect=${expectKey} (use baseline|final)\n`,
  );
  process.exit(2);
}

let tempDir = null;
let result;

try {
  tempDir = mkdtempSync(join(tmpdir(), 'loombre-ui-audit-'));
  const probeFile = join(tempDir, 'planted-probe.css');
  writeFileSync(probeFile, PROBE_CSS, 'utf8');

  const bin = existsSync(LOCAL_BIN) ? LOCAL_BIN : 'npx';
  const argv = existsSync(LOCAL_BIN)
    ? ['--config', CONFIG, '--formatter', 'json', probeFile]
    : ['stylelint', '--config', CONFIG, '--formatter', 'json', probeFile];

  // stylelint exits 2 when it reports problems — that is the SUCCESS path here,
  // so the payload is read off the thrown error too. It also routes the report
  // to STDERR on a non-zero exit (stdout is empty), so both streams are tried.
  // Only a missing/broken binary or an unparseable payload is a real failure.
  let payload = '';
  try {
    // stdio must be pipe on all three: node's *Sync helpers forward the child's
    // stderr to the parent's by default, which would dump stylelint's raw JSON
    // into this script's own output.
    payload = execFileSync(bin, argv, {
      cwd: WEB_DIR,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch (err) {
    const candidate = [err.stdout, err.stderr].find(
      (s) => typeof s === 'string' && s.trim().startsWith('['),
    );
    if (candidate === undefined) throw err;
    payload = candidate;
  }

  const parsed = JSON.parse(payload);
  const warnings = parsed.flatMap((f) => f.warnings ?? []);

  const flagged = (property, value) =>
    warnings.some((w) => {
      const t = String(w.text ?? '');
      // Rule-agnostic on purpose: W2-B may implement the gap law with
      // declaration-property-value-allowed-list, a disallowed-list, or a
      // custom plugin. What matters is that SOMETHING rejects the value on
      // that property, on that line.
      const line = PROBE_CSS.split('\n').findIndex((l) =>
        l.trim().startsWith(`${property}:`),
      ) + 1;
      const mentionsValue = t.includes(value);
      const mentionsProperty = t.includes(property);
      return (mentionsValue && mentionsProperty) || (w.line === line && mentionsValue);
    });

  result = {
    checkedAt: new Date().toISOString(),
    stylelintBinary: existsSync(LOCAL_BIN)
      ? 'apps/web/node_modules/.bin/stylelint'
      : 'npx stylelint',
    config: 'apps/web/.stylelintrc.json',
    probeCss: PROBE_CSS,
    radiusCaught: flagged('border-radius', '11px'),
    gapCaught: flagged('gap', '13px'),
    warnings: warnings.map((w) => ({ line: w.line, rule: w.rule, text: w.text })),
  };
} finally {
  if (tempDir) rmSync(tempDir, { recursive: true, force: true });
}

const expected = expectKey ? EXPECTATIONS[expectKey] : null;
const matches = expected
  ? expected.radiusCaught === result.radiusCaught &&
    expected.gapCaught === result.gapCaught
  : null;

result.expect = expectKey;
result.expected = expected;
result.matchesExpectation = matches;

if (jsonOut) {
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
} else {
  const lines = [];
  lines.push('UI-AUDIT PLANTED-VIOLATION CHECK — run UIFIX-2026-08-29');
  lines.push(`at:     ${result.checkedAt}`);
  lines.push(`binary: ${result.stylelintBinary}`);
  lines.push(`config: ${result.config}`);
  lines.push('');
  lines.push('probe CSS (written to a temp dir, removed after the run):');
  for (const l of PROBE_CSS.replace(/\n$/, '').split('\n')) lines.push(`  ${l}`);
  lines.push('');
  lines.push(`  radiusCaught = ${result.radiusCaught}   (border-radius: 11px rejected?)`);
  lines.push(`  gapCaught    = ${result.gapCaught}   (gap: 13px rejected?)`);
  lines.push('');
  lines.push('stylelint warnings observed:');
  if (result.warnings.length === 0) lines.push('  (none)');
  for (const w of result.warnings) lines.push(`  line ${w.line}  [${w.rule}]  ${w.text}`);
  lines.push('');
  if (expected) {
    lines.push(
      `expectation --expect=${expectKey}: radiusCaught=${expected.radiusCaught}, gapCaught=${expected.gapCaught}`,
    );
    lines.push(matches ? 'RESULT: MATCHES expectation' : 'RESULT: MISMATCH');
  } else {
    lines.push('no --expect given — reporting only, exit 0');
    lines.push('TODAY the expected state is --expect=baseline (radius true, gap false);');
    lines.push('after W2-B lands the spacing-scale rule, gates switch to --expect=final.');
  }
  process.stdout.write(`${lines.join('\n')}\n`);
}

process.exit(matches === false ? 1 : 0);
