// SPDX-License-Identifier: AGPL-3.0-only
// Loombre :: apps/worker/test/stash/fixtures/build-fixture-db.ts
//
// Committed helper (S3: "checked-in schema fixtures per supported
// version... generated by a committed script into test fixtures") that
// materializes a real SQLite database file from one of this directory's
// checked-in `.sql` DDL+seed text fixtures. The `.sql` text is what's
// checked into git (small, diffable, reviewable); the `.sqlite` binary it
// produces is built fresh at test time into a temp directory, mirroring
// the repo's existing test-fixtures/media/ convention of never committing
// generated binary artifacts.

import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';

/** Executes the given `.sql` fixture file's full DDL+seed script against a
 *  freshly created SQLite database at `outputDbPath`, and returns an open
 *  (read-write) handle to it — callers that want a READ-ONLY handle (the
 *  normal case: proving the adapter/guard/read-model against a fixture)
 *  should close this one and reopen via
 *  apps/worker/src/stash/adapter.ts's openStashConnection, exactly as they
 *  would for a real Stash database. */
export function buildFixtureDb(sqlFixturePath: string, outputDbPath: string): DatabaseSync {
  const sql = readFileSync(sqlFixturePath, 'utf8');
  const db = new DatabaseSync(outputDbPath);
  db.exec(sql);
  return db;
}
